if vim.g.loaded_pi_nvim then
  return
end
vim.g.loaded_pi_nvim = true

vim.api.nvim_create_user_command("PiContextAdd", function(opts)
  require("pi").context_add(opts)
end, { range = true, nargs = "*", desc = "Add saved context to the Pi draft" })
vim.api.nvim_create_user_command("PiContextShow", function()
  require("pi").context_show()
end, { desc = "Show the Pi context draft" })
vim.api.nvim_create_user_command("PiContextRemove", function()
  require("pi").context_remove()
end, { desc = "Remove a Pi context item" })
vim.api.nvim_create_user_command("PiContextRefresh", function()
  require("pi").context_refresh()
end, { desc = "Refresh a Pi context item" })
vim.api.nvim_create_user_command("PiContextClear", function()
  require("pi").context_clear()
end, { desc = "Clear the Pi context draft" })
vim.api.nvim_create_user_command("PiContextMove", function(opts)
  require("pi").context_move(opts)
end, { nargs = 1, desc = "Move the draft item at cursor to a position" })
vim.api.nvim_create_user_command("PiContextSend", function()
  require("pi").context_send()
end, { desc = "Send the Pi context draft" })
vim.api.nvim_create_user_command("PiSend", function(opts)
  require("pi").send_current(opts)
end, { range = true, nargs = "*", desc = "Send current saved context to Pi" })
vim.api.nvim_create_user_command("PiAttach", function()
  require("pi").attach()
end, { desc = "Attach an opted-in Pi terminal session" })
vim.api.nvim_create_user_command("PiSessions", function()
  require("pi").sessions()
end, { desc = "Show Pi sessions" })
vim.api.nvim_create_user_command("PiFindings", function()
  require("pi").findings()
end, { desc = "Show Pi findings" })
vim.api.nvim_create_user_command("PiReply", function()
  require("pi").reply()
end, { desc = "Reply to a Pi finding" })
vim.api.nvim_create_user_command("PiClear", function()
  require("pi").clear()
end, { desc = "Clear Pi findings" })
vim.api.nvim_create_user_command("PiResponse", function()
  require("pi").response()
end, { desc = "Open the latest headless Pi response" })
vim.api.nvim_create_user_command("PiStatus", function()
  require("pi").status()
end, { desc = "Show Pi bridge status" })
vim.api.nvim_create_user_command("PiStop", function()
  require("pi").stop()
end, { desc = "Stop the headless Pi worker" })
